# Generated by Django 3.1.6 on 2021-02-07 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='author',
            new_name='name',
        ),
    ]
