# Generated by Django 3.1.6 on 2021-02-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme', '0002_auto_20210207_0827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meme',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
