# Generated by Django 3.1.6 on 2021-02-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmeme', '0003_auto_20210209_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='url',
            field=models.URLField(),
        ),
    ]
